<?php

    class SETTINGS{

        public static $IS_HTML = TRUE;
        public static $SECURE = "tls";
        public static $SMTP_HOST = "smtp.gmail.com";
        public static $SMTP_PORT = "587";
        public static $SMTP_USER = "SMTP USERNAME";
        public static $SMTP_PASSWORD = "SMTP PASSWORD";

        public static $TITLE = "Akasya Bilişim";
        public static $SENDER_MAIL =  "byhackro@gmail.com";
        public static $ADMIN_MAIL =  "musaatalay@mail.com.tr";

    }

?>